name: Local Deployment Pipeline

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Install dependencies
        run: pip install -r requirements.txt

      #- name: Run tests
       # run: pytest

      - name: Build Docker image
        run: docker build -t my-flask-app .

      - name: Run Docker container
        run: docker run -it -p 5000:5000 my-flask-app

      - name: Test Docker deployment
        run: |
          sleep 5  # Give the server some time to start
          curl http://localhost:5000/predict  # Test the deployed endpoint
